version: '3.0'
services:
  mysql:
    image: mysql:latest
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names = 1
    healthcheck:
      test: ["CMD", "root" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  admin-api:
    image: openjdk:14
    env_file: .env
    volumes:
      - ./run.sh:/home/eat/run.sh
      - ./eat-admin-api/build/libs:/home/eat/libs
    ports:
      - 8002:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/eat && sh run.sh"
